---
title: "Oaxaca ONUSIDA"
author: "Isaac Núñez, Yanink Caro-Vega"
output:
  word_document: default
  html_document:
    df_print: paged
---
```{r include= T, run = T}
#El presente reporte consiste en una descripción de la atención que se brinda a personas que viven con VIH dentro del sistema 'CAPASITS' del estado de Oaxaca con una perspectiva de sistemas. Incluimos lo acordado en el plan de análisis cuantitativo propuesto previamente. En base a la información que se encontró disponible, se describen las interrogantes que si pudieron responderse, cuales no pudieron responderse, y las limitantes en ambos casos en cuanto a la capacidad de los datos conseguidos para contestar las preguntas de interés.
```



```{r setup, include = T, warning=F}
setwd("C:/Users/isaac/OneDrive/Documentos/Protocolos_de_investigacion/Chiapas-Oaxaca ONUSIDA")

library(tidyverse);library(lubridate); library(readxl);library(viridis);library(data.table);library(devtools)
#library(mxmaps)


```


```{r importación de bases, include = T, warning=F}
epi_oaxaca <- read_excel("base_oaxaca_21.xlsx") %>% 
  mutate(id_paciente=as.character(id_paciente),
         paciente_ultima_consulta = ymd(paciente_ultima_consulta),
         paciente_notificacion = ymd(paciente_notificacion),
         paciente_ingreso = ymd(paciente_ingreso),
         paciente_fecha_defuncion = ymd(paciente_fecha_defuncion),
         paciente_fecha_alta = ymd(substr(paciente_fecha_alta, 1, 10)),
         paciente_f_ultimo_estatus = ymd(substr(paciente_f_ultimo_estatus, 1, 10)),
         esquema_fecha_inicio = ymd(esquema_fecha_inicio),
         cv_fecha_estudio = ymd(cv_fecha_estudio))

#save(epi_oaxaca, file="epi_oaxaca.Rda")

## Descripción de la base  

```
Recibimos la base 'OAXACA PROYECTO 21' con `r ncol(epi_oaxaca)` variables y `r nrow(epi_oaxaca)` observaciones. 

```{r pacientes y sexo, include = T, warning = F}
#####ANÁLISIS DE BASE PRELIMINAR

######La base quedó con el nombre'epi_oaxaca'
glimpse(epi_oaxaca)

######Número de filas
nrow(epi_oaxaca)

######Número de identificadores diferentes
n_distinct(epi_oaxaca$id_paciente)
#Hay 5921 filas y 5920 identificadores diferentes
glimpse(epi_oaxaca %>% 
  group_by(id_paciente) %>% 
    count() %>% 
  arrange(desc(n)))[1,1] 
#51151 es el paciente que se repite
glimpse(filter(epi_oaxaca, id_paciente == 51151))#Únicamente difieren en el esquema de ART que está utilizando, por lo pronto no lo eliminaré

######Pacientes en tratamiento ART ('paciente_tipo' según la variable de la base)
table(epi_oaxaca$paciente_tipo)
#Al parecer todos los pacientes están clasificados como en tratamiento antirretroviral

######Sexo 
table(epi_oaxaca$paciente_sexo)

#Únicamente confirmar que 'TF' signifique mujer trans y que 'TM' signifique hombre trans
```

```{r include= T, run = F}
#La base cuenta con una fila por paciente y una columna por variable, con solo un paciente repetido (aquel con el identificador `r glimpse(epi_oaxaca %>%group_by(id_paciente) %>% count() %>%arrange(desc(n)))[1,1]`). Las variables incluidas son las siguientes: `r names(epi_oaxaca)`.  

#Según se puede inferir de la base, incluye la información más actualizada al momento en el cual se generó. Es decir, incluye algunas características basales(por ejemplo, 'fecha de ingreso') y otras que corresponden a la última medición para una variable determinada (por ejemplo, 'cd4 resultado').
```




```{r base oaxaca v1, include = T, warning = F}
#####Edad
fivenum(epi_oaxaca$paciente_edad)
nrow(filter(epi_oaxaca, paciente_edad>=18))
nrow(filter(epi_oaxaca, paciente_edad>=18))/nrow(epi_oaxaca)
#Prácticamente todos son mayores de edad
#La distribución de la edad parece razonable, pero si se puede lo mejor sería que nos dieran la fecha de nacimiento, desconozco cuándo y cómo actualicen la edad de los pacientes


#####Pacientes con VIH que están embarazadas (habría que preguntar exactamente cómo definen esta variable y con qué frecuencia la actualizan)
table(epi_oaxaca$paciente_vih_embarazada)
#Descartar que haya errores de código en cuanto a sexo
table(EMBARAZADA = epi_oaxaca$paciente_vih_embarazada,
      SEXO = epi_oaxaca$paciente_sexo)
#Parece que al hombre trans lo pusieron como 'NO APLICA'. Es un detalle pequeño, pero creo que valdría la pena que actualizaran esta codificación en su estado porque el término preferido actual es 'personas con capacidad de gestar' (nada más confirmar que por el hecho de ser trans no les asignen la variable de 'NO APLICA')
#Hay 73 hombres que se clasificaron como 'NO' embarazadas, verificar si esto simplemente fue por error al meter los datos (ej. no sabían que se tenían que poner en 'NO APLICA' o si son hombres trans)


######Última consulta
range(epi_oaxaca$paciente_ultima_consulta)#Hay pacientes sin info en última consulta
sum(is.na(epi_oaxaca$paciente_ultima_consulta))#Solo es uno
glimpse(filter(epi_oaxaca, is.na(paciente_ultima_consulta)))
#Parece que si tiene último estatus, nomás no tiene fecha de última consulta, según los datos parece que en cuanto se captó se sacó del programa porque tenía ISSSTE, por el momento no creo que haya que excluirlo

range(epi_oaxaca$paciente_ultima_consulta[!is.na(epi_oaxaca$paciente_ultima_consulta)])#Fecha de última consulta con rango implausible
range(epi_oaxaca$paciente_ultima_consulta[!is.na(epi_oaxaca$paciente_ultima_consulta)&
                                            epi_oaxaca$paciente_ultima_consulta>="2000-01-01"])#Última fecha de consulta introducida en la base con la fecha más temprana (aparentemente real que no parece un error de codificación) en 2005

nrow(filter(epi_oaxaca, paciente_ultima_consulta>="2000-01-01"))#Únicamente dos pacientes con fecha de consulta previo a este año, uno de los cuales es el paciente con valor faltante en esa variable

#La mayoría de pacientes tuvieron su última consulta en 2021
epi_consulta <- mutate(epi_oaxaca, year_ultima_consulta=year(paciente_ultima_consulta)) %>% 
  group_by(year_ultima_consulta) %>% 
  count() %>% 
  mutate(year_ultima_consulta=as.factor(year_ultima_consulta))

epi_consulta$n[epi_consulta$year_ultima_consulta ==2021]/sum(epi_consulta$n)
#Dos tercios de pacientes tuvieron su última consulta en 2021
ggplot(epi_consulta, aes(y=year_ultima_consulta, x = n))+
  theme_bw()+
  ggtitle("Año de última consulta en COESIDA de personas que viven con VIH")+
  ylab("Año de última consulta")+
  xlab("Número de pacientes")+
  geom_segment(aes(yend = year_ultima_consulta), xend=0, colour="grey50", size = 1.5)+  
  geom_point(size = 3.5, colour = "red")+
  scale_x_continuous(breaks= seq(from = 0, to = 4000, by =250))+
  theme(axis.text.x = element_text(angle=30))
  

######Pacientes privados de su libertad
table(epi_oaxaca$paciente_priv_libertad)
#Pocos pacientes privados de su libertad
table(PRIVADOS_LIBERTAD=epi_oaxaca$paciente_priv_libertad,
      SEXO=epi_oaxaca$paciente_sexo)
#Distinción por sexo, a destacar que parece que no hay pacientes trans, lo cual podría significar a su vez algo bastante malo


######Paciente notificación. No estoy seguro que significa, será la fecha de diagnóstico?
range(epi_oaxaca$paciente_notificacion)#Algunos no tienen ese dato
sum(is.na(epi_oaxaca$paciente_notificacion))#Sólo 4
glimpse(filter(epi_oaxaca, is.na(paciente_notificacion)))#No encuentro una causa obvia para la falta de este dato, supongo que fue únicamente error al meter la información
range(epi_oaxaca$paciente_notificacion[!is.na(epi_oaxaca$paciente_notificacion)])#Primera fecha de notificación en 1984, no creo que sea esta la fecha del primer caso de VIH en oaxaca, o sí? Habría que revisar

epi_notificacion <- mutate(epi_oaxaca, year_paciente_notificacion=year(paciente_notificacion)) %>% 
  group_by(year_paciente_notificacion) %>% 
  count() %>% 
  mutate(year_paciente_notificacion=as.factor(year_paciente_notificacion))

epi_notificacion$n[epi_notificacion$year_paciente_notificacion ==2021]/sum(epi_notificacion$n)
#Sólo 7% se notificaron en 2021, supongo que si es la fecha de diagnóstico, pero habría que confirmar con quienes armaron la base
ggplot(epi_notificacion, aes(y=year_paciente_notificacion, x = n))+
  theme_bw()+
  ggtitle("Año de notificación (diagnóstico?) de personas que viven con VIH en Oaxaca")+
  ylab("Año de notificación")+
  xlab("Número de pacientes")+
  geom_segment(aes(yend = year_paciente_notificacion), xend=0, colour="grey50", size = 1.5)+  
  geom_point(size = 3.5, colour = "red")+
  scale_x_continuous(breaks= seq(from = 0, to = 500, by =50))+
  theme(axis.text.x = element_text(angle=30))


#####Paciente ingreso
range(epi_oaxaca$paciente_ingreso)#Algunos no tienen ese dato
sum(is.na(epi_oaxaca$paciente_ingreso))#Sólo 14
glimpse(filter(epi_oaxaca, is.na(paciente_ingreso)))#No encuentro una causa obvia para la falta de este dato, supongo que fue únicamente error al meter la información
range(epi_oaxaca$paciente_ingreso[!is.na(epi_oaxaca$paciente_ingreso)])#Primera fecha de ingreso en 1994, este año se fundó COESIDA entonces supongo que si es únicamente referente a este servicio

epi_ingreso <- mutate(epi_oaxaca, paciente_ingreso=year(paciente_ingreso)) %>% 
  group_by(paciente_ingreso) %>% 
  count() %>% 
  mutate(paciente_ingreso=as.factor(paciente_ingreso))

epi_ingreso$n[epi_ingreso$paciente_ingreso ==2021]/sum(epi_ingreso$n)
#Sólo 7% ingresaron en 2021 (igual que el número de notificaciones/diagnósticos)

ggplot(epi_ingreso, aes(y=paciente_ingreso, x = n))+
  ggtitle("Año de ingreso a COESIDA de personas que viven con VIH")+
  theme_bw()+
  ylab("Año de ingreso")+
  xlab("Número de pacientes")+
  geom_segment(aes(yend = paciente_ingreso), xend=0, colour="grey50", size = 1.5)+  
  geom_point(size = 3.5, colour = "red")+
  scale_x_continuous(breaks= seq(from = 0, to = 500, by =50))+
  theme(axis.text.x = element_text(angle=30))
#Parece que ninguno se inactivó por la pandemia, al menos durante algún año completo


#####Paciente SAI (centro de atención)
table(epi_oaxaca$paciente_sai)
#Parece que sólo hay dos centros

#Aquí quiero ver si los dos han estado siempre activos o si francamente alguno dejó de recibir pacientes en algún momento
epi_sai <- mutate(epi_oaxaca, paciente_ingreso=year(paciente_ingreso)) %>% 
  group_by(paciente_sai, paciente_ingreso) %>% 
  count() %>% 
  mutate(paciente_ingreso=as.factor(paciente_ingreso))


ggplot(epi_sai, aes(y=paciente_ingreso, x = n, fill = paciente_sai))+
  ggtitle("Año de ingreso a COESIDA según SAI")+
  theme_bw()+
  ylab("Año de ingreso")+
  xlab("Número de pacientes")+
  geom_col(position=position_dodge(0.5), colour = "black")+  
  scale_x_continuous(breaks= seq(from = 0, to = 500, by =50))+
  theme(axis.text.x = element_text(angle=30))
#Parece que ningún SAI dejó de funcionar (al menos durante un periodo prolongado)


#####Paciente fecha alta 
sum(is.na(epi_oaxaca$paciente_fecha_alta))
#parece que todos tienen este dato. ¿A qué se refieren con fecha de alta? Definitivamente no es alta médica, ya que todas las persoans lo tienen, tampoco es fecha de ingreso porque difiere a la otra en las fechas
range(epi_oaxaca$paciente_fecha_alta)


######Estatus de los pacientes
table(epi_oaxaca$paciente_estatus)
#Habría que preguntar qué significan los siguientes dos estatus:
#'EN DERIVACION DERECHOHABIENCIA"
#'EN SUSPENSION'
#Además, cuáles son los criterios para cada uno de los estados. ¿Cambiaron estos criterios con la pandemia? ¿Hubo algún periodo de inactividad en el cual no se actualizó el estatus de los pacientes (o peor, que el sistema de atención se mantuvo inactivo, al menos durante algunas semanas-meses)?


#####Paciente causa baja
table(epi_oaxaca$paciente_causa_baja)
#Cómo determinan que alguien se da de alta médica? Formalmente una persona que vive con VIH nunca está de alta médica. Cómo definieron abandono? Es posible que estos abandonos sean defunciones o migraciones no detectadas?


#####Paciente fecha de defunción
sum(!is.na(epi_oaxaca$paciente_fecha_defuncion))
#Este número (658) difiere al número de defunciones totales que tienen registradas (848), hay algún motivo por el cuál no se tenga la fecha de defunción?
table(DEFUNCION_CON_FECHA=!is.na(epi_oaxaca$paciente_fecha_defuncion),
      CAUSA_DE_BAJA=epi_oaxaca$paciente_causa_baja)
#Aquí nomás podemos reclasificar a un paciente que tiene como causa de baja "ABANDONO" pero tiene una fecha de muerte
#Quizá con la fecha de último estatus


#Fecha de últimop estatus
range(epi_oaxaca$paciente_f_ultimo_estatus)
#Todos tienen este dato, alguno de los que fallecieron tendrá una fecha posterior a la de muerte (o viceversa)?

nrow(filter(epi_oaxaca, (!is.na(paciente_fecha_defuncion)|paciente_causa_baja=="DEFUNCION")& paciente_f_ultimo_estatus>paciente_fecha_defuncion))
#641 de quienes fallecieron tienen una fecha de úlimo estatus posterior a la fecha de muerte, en qué consta la fecha de últimoe estatus?

nrow(filter(epi_oaxaca, (!is.na(paciente_fecha_defuncion)|paciente_causa_baja=="DEFUNCION")& paciente_f_ultimo_estatus<paciente_fecha_defuncion))
#Sólo 5 tienen una fecha de muerte posterior a la de último estatus, esto es más fácil de explicar y corregir


#Esquema fecha inicio
range(epi_oaxaca$esquema_fecha_inicio)#Personas sin ese dato
sum(is.na(epi_oaxaca$esquema_fecha_inicio))#Sólo 70, tienen perdida la fecha de inicio de esquema o realmente nunca lo iniciaron?
glimpse(filter(epi_oaxaca, is.na(epi_oaxaca$esquema_fecha_inicio)))
#Sería interesante, una vez confirmado que la variable "paciente notificacion" corresponda a la fecha de diagnóstico, analizar cuánto tiempo tardaron en iniciar ARV desde el diagnóstico (que será lo que haremos con los datos de ccasanet, de aceptarlo Sierra, Brenda, y los demás de ccasanet)


#####CD4
sum(is.na(epi_oaxaca$cd4_resultado))#270 nunca han tenido una toma de CD4 (quiero pensar que el valor incluido en esta base es el último para cada persona)
#Sería estupendo que nos pasaran el resto de los CD4 para cada persona (igual que la CV)


#####Carga viral
sum(is.na(epi_oaxaca$cv_no_copias))#304 nunca han tenido una cv, por qué difiere este número al de linfocitos CD4?

```

```{r base capasits, warning=F, include= F}
plantilla_capasits <- read_excel("PLANTILLA POR CAPASITS DE OAXACA2.xlsx") %>% 
  mutate(paciente_ultima_consulta= ymd(paciente_ultima_consulta),
         paciente_notificacion= ymd(paciente_notificacion),
         paciente_ingreso=ymd(paciente_ingreso),
         paciente_fecha_alta=ymd(paciente_fecha_alta),
         paciente_f_ultimo_estatus=ymd(substr(paciente_f_ultimo_estatus, 1, 10)),
         esquema_fecha_inicio=ymd(esquema_fecha_inicio),
         cd4_fecha_estudio=ymd(cd4_fecha_estudio),
         cv_fecha_estudio=ymd(cv_fecha_estudio)) 

nrow(plantilla_capasits)

plantilla_capasits_filtrada <- filter(plantilla_capasits, (paciente_f_ultimo_estatus>="2018-01-01"|
                 esquema_fecha_inicio>="2018-01-01"|
                 paciente_ingreso>="2018-01-01"|
                 paciente_notificacion>="2018-01-01"|
                 paciente_ultima_consulta>="2018-01-01"|
                 cd4_fecha_estudio>="2018-01-01"|
                 cv_fecha_estudio>="2018-01-01"|
                   paciente_fecha_alta>="2018-01-01")&
                   (is.na(paciente_fecha_defuncion)|
                   (!is.na(paciente_fecha_defuncion)&paciente_fecha_defuncion>="2018-01-01")))


nrow(plantilla_capasits_filtrada)

nrow(filter(plantilla_capasits_filtrada, paciente_f_ultimo_estatus<"2018-01-01"&
                 esquema_fecha_inicio<"2018-01-01"&
                 paciente_ingreso<"2018-01-01"&
                 paciente_notificacion<"2018-01-01"&
                 paciente_ultima_consulta<"2018-01-01"&
                 cd4_fecha_estudio<"2018-01-01"&
                 cv_fecha_estudio<"2018-01-01"&
                   paciente_fecha_alta<"2018-01-01"&
              (is.na(paciente_fecha_defuncion)|!is.na(paciente_fecha_defuncion)&paciente_fecha_defuncion<"2018-01-01")))

#write.csv(plantilla_capasits_filtrada, "./plantilla_capasits_filtrada.csv", row.names=T)
```

